### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [ozwaldorf/lutgen-rs#16]
Dear @ozwaldorf, is there a chance that you will make your program available to a wider audience by releasing an executable file for Windows 7 x64?

**Comment by ozwaldorf** [comment]
Can you try this build?
[x86_64-pc-windows-gnu.tar.gz](https://github.com/ozwaldorf/lutgen-rs/files/14283773/x86_64-pc-windows-gnu.tar.gz)

**Comment by ozwaldorf** [comment]
Added to the last release, and I'll start building these for future releases

**Comment by sergeevabc** [comment]
> Added to the last release, and I'll start building these for future releases

0.9.0 works fine on my end, but [0.10.0](https://github.com/ozwaldorf/lutgen-rs/releases/tag/v0.10.0) has no Windows build.

**Comment by ozwaldorf** [comment]
> > Added to the last release, and I'll start building these for future releases
> 
> 0.9.0 works fine on my end, but [0.10.0](https://github.com/ozwaldorf/lutgen-rs/releases/tag/v0.10.0) has no Windows build.

Fixed! Setup a CI builder I can dispatch on any revision to easily build this for releases

**Comment by sergeevabc** [comment]
> See https://blog.rust-lang.org/2024/02/26/Windows-7.html

Yep, it makes me sad. Go, Python, Rust programming languages turned out to be modern Trojan horses. Under the guise of progress, they have become a tool for dividing people into classes: the golden billion and the rest. Thank goodness this did not affect C language, for its apps can still be compiled for the widest range of hardware and operating systems, including Windows 7.

> Added a `legacy-windows` binary built with rustc 1.77.2

Thank you for staying true to the mission of helping humanity through technology.
