### ISSUE TITLE
The option `--output` creates a directory for single files

### ISSUE THREAD

**Issue by LovingMelody** [ozwaldorf/lutgen-rs#17]
**Describe the bug**
When running lutgen with the `--output` flag, a directory is created with the specified output as the name, docs states this should only be done if its more than one file

**To Reproduce**
1. Take an image
2. lutgen  apply wallpaper.png -o edited-wallpaper.png -p catppuccin-mocha

**Expected behavior**
Lutgen creates the image with the file name what was passed to `-o` and not a directory

**Environment (please complete the following information):**
 - OS:NixOS
 - Lutgen Version [0.10.0]

**Additional context**
This issue was not present in version 0.9.0

**Comment by ozwaldorf** [comment]
Should be fixed with 1313e204
