### ISSUE TITLE
Apply Every Palette to a Single Image

### ISSUE THREAD

**Issue by Atrament1s** [ozwaldorf/lutgen-rs#20]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to see how a variety of palettes look on a single image, but it can be hard to pick which color palettes would look best, since I'm not familiar with the majority of them. 

**Describe the solution you'd like**
It'd be awesome if there were an option to apply every palette on a single image. An example of how this could look would be `lutgen apply -p all <image>.png`. This would create a folder named <image> with each applied image being named <image>-<palette>. For example, for `lutgen apply -p all astronaut.png`:

astronaut
├astronaut-gruvbox-dark.png
├astronaut-gruvbox-light.png
├astronaut-rose-pine.png
├astronaut-catppuccin-macchiato.png
...
└astronaut-mono-green-gogh.png

**Describe alternatives you've considered**
An alternative may be to write a bash script to run lutgen for every color palette supported, however a built-in solution would be not only more convenient, but would also see more use than a script, since the option is built-in.

**Comment by ozwaldorf** [comment]
This should be possible with something like:
```bash
mkdir image
lutgen palette names | while read pal; do
  lutgen apply -p $pal image.png
done
```

**Comment by Atrament1s** [comment]
It works great, thanks!
