### ISSUE TITLE
FEATURE REQUEST: Bash completion

### ISSUE THREAD

**Issue by tsukki9696** [ozwaldorf/lutgen-rs#3]
Would be helpful to have completion/autosuggest for the different flags and options of `lutgen` since the CLI is loaded with features and sometimes it's hard to remember the name of a specific option or color palette. That or a `manpage` would be great additions to the project.

**Comment by ozwaldorf** [comment]
Done! ff7fa2e adds a completions flag to the bin for bash, zsh, fish, powershell, and elvish. The flag will make the binary output the corresponding completions script, which you can place in the corresponding location for that shell

**Comment by ozwaldorf** [comment]
Reopening because I want to add automatic installation of the completions for the packaged release

**Comment by ozwaldorf** [comment]
released lutgen-git on aur, which installs autocompletions along with latest git

**Comment by ozwaldorf** [comment]
Released v0.7.0 with the functionality! All aur packages install the completions for you (-bin, -git)

**Comment by tsukki9696** [comment]
thank you! glad to see a suggestion turning into an actual feature, keep up the amazing work :pray:
